// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sSe8AoDiAW5DkmycE76RKb
// Component: 6BXtrSevg1h6js
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import * as ph from "@plasmicapp/host"
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"
import Header from "../../Header" // plasmic-import: rlLZVswJyeOUp/component
import ServicesWhite from "../../ServicesWhite" // plasmic-import: q3dvYXhBAjM3ih/component
import Footer from "../../Footer" // plasmic-import: aKMJC5Su_PgNb/component
import { useScreenVariants as useScreenVariantsxe8Uhzv7PeLJgW } from "./PlasmicGlobalVariant__Screen" // plasmic-import: XE8Uhzv7PeLJgW/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css"
import * as projectcss from "./plasmic_rva_new.module.css" // plasmic-import: sSe8AoDiAW5DkmycE76RKb/projectcss
import * as sty from "./PlasmicServices.module.css" // plasmic-import: 6BXtrSevg1h6js/css
import woman32879561920JpgE5H1EGp7Yidpwp from "./images/woman32879561920Jpg.jpeg" // plasmic-import: E5H1eGp7yidpwp/picture

export const PlasmicServices__VariantProps = new Array()

export const PlasmicServices__ArgProps = new Array()

export const defaultServices__Args = {}

function PlasmicServices__RenderFunc(props) {
  const { variants, overrides, forNode } = props
  const args = Object.assign({}, defaultServices__Args, props.args)
  const $props = args
  const $ctx = ph.useDataEnv?.() || {}
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsxe8Uhzv7PeLJgW(),
  })

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"pageBanerSection"}
            data-plasmic-override={overrides.pageBanerSection}
            className={classNames(projectcss.all, sty.pageBanerSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__sfrl6)}>
              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                {"Services"}
              </h1>
            </div>
          </div>

          <section className={classNames(projectcss.all, sty.section__hBd2K)}>
            <div className={classNames(projectcss.all, sty.freeBox__rnTT)}>
              <div className={classNames(projectcss.all, sty.freeBox__dtBcc)}>
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__w7RnU)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.columns__iy5Ev)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___2Kegg
                        )}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__rGd6D
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__cyl0M
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__ikN4H
                        )}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__wUvVs
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__wfNFz
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__w8Q2L
                        )}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__fu9Jr
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__i5VKw
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__oOo3J
                        )}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__fW0So
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__qSq2W
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__krE2S
                        )}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__sqJ9Y
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__uxdSa
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__lhW3O
                        )}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__ibope
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__oqXzi
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>
                    </p.Stack>
                  </p.Stack>
                ) : null}
              </div>
            </div>
          </section>

          <section className={classNames(projectcss.all, sty.section__fntra)}>
            <h2
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2__mXfRq
              )}
            >
              {hasVariant(globalVariants, "screen", "mobileOnly")
                ? "Why Choose Us"
                : "Our process"}
            </h2>

            <div className={classNames(projectcss.all, sty.freeBox__agmef)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__vgOMl)}
              >
                <div className={classNames(projectcss.all, sty.column__ud34O)}>
                  <ServicesWhite
                    className={classNames(
                      "__wab_instance",
                      sty.servicesWhite___6RDV
                    )}
                    slot={
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__iPv7U
                        )}
                      >
                        {"Services main"}
                      </h3>
                    }
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__mjGbF)}>
                  <ServicesWhite
                    className={classNames(
                      "__wab_instance",
                      sty.servicesWhite__wYtpw
                    )}
                    slot={
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__jE3BJ
                        )}
                      >
                        {"Services main"}
                      </h3>
                    }
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__lsg8W)}>
                  <ServicesWhite
                    className={classNames(
                      "__wab_instance",
                      sty.servicesWhite__qBwHd
                    )}
                    slot={
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__vamV
                        )}
                      >
                        {"Services main"}
                      </h3>
                    }
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__uUtG)}>
                  <ServicesWhite
                    className={classNames(
                      "__wab_instance",
                      sty.servicesWhite__hNp63
                    )}
                    slot={
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__w6QwO
                        )}
                      >
                        {"Services main"}
                      </h3>
                    }
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__gHywc)}>
                  <ServicesWhite
                    className={classNames(
                      "__wab_instance",
                      sty.servicesWhite__sxyTt
                    )}
                    slot={
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__ahAb2
                        )}
                      >
                        {"Services main"}
                      </h3>
                    }
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__lyTlI)}>
                  <ServicesWhite
                    className={classNames(
                      "__wab_instance",
                      sty.servicesWhite__cY7JC
                    )}
                    slot={
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__d1T8A
                        )}
                      >
                        {"Services main"}
                      </h3>
                    }
                  />
                </div>
              </p.Stack>
            </div>
          </section>

          <section className={classNames(projectcss.all, sty.section__wBuuj)}>
            <div className={classNames(projectcss.all, sty.freeBox___4T7A)}>
              <div className={classNames(projectcss.all, sty.freeBox__rHuq2)}>
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__nKc41)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.columns__awmg3)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___2HuaM
                        )}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__kfY7Z
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__jehEm
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__ycAh1
                        )}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__xhZq1
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__rsg8I
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__frikl
                        )}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__uns65
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__fhNyG
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___5YdWz
                        )}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__a239T
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3___0Xrd
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__is3Uu
                        )}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__rvfJz
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__oRgO
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__n9VjQ
                        )}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__b6Gl
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__gVrJ
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>
                    </p.Stack>
                  </p.Stack>
                ) : null}
              </div>
            </div>
          </section>

          <section className={classNames(projectcss.all, sty.section__gMtel)}>
            <div className={classNames(projectcss.all, sty.freeBox__tlQUm)}>
              <div className={classNames(projectcss.all, sty.freeBox__xrpEb)}>
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__qoB1Q)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.columns__wcLx)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__b9XpV
                        )}
                      >
                        <p.PlasmicImg
                          data-plasmic-name={"img"}
                          data-plasmic-override={overrides.img}
                          alt={""}
                          className={classNames(sty.img)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: woman32879561920JpgE5H1EGp7Yidpwp,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined,
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__ojXjw
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___0Ca5V
                          )}
                        >
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2__g8Wjr
                            )}
                          >
                            {"Why Choose Us"}
                          </h2>

                          <div
                            data-plasmic-name={"text"}
                            data-plasmic-override={overrides.text}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam"
                            }
                          </div>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.columns__fLoaI
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column__ddNl
                              )}
                            >
                              <ServicesWhite
                                className={classNames(
                                  "__wab_instance",
                                  sty.servicesWhite__tKcXe
                                )}
                                slot={
                                  <h3
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h3,
                                      projectcss.__wab_text,
                                      sty.h3__skv9P
                                    )}
                                  >
                                    {"Services main"}
                                  </h3>
                                }
                              />
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column__tyu3G
                              )}
                            >
                              <ServicesWhite
                                className={classNames(
                                  "__wab_instance",
                                  sty.servicesWhite__k3Dxq
                                )}
                                slot={
                                  <h3
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h3,
                                      projectcss.__wab_text,
                                      sty.h3__poAi4
                                    )}
                                  >
                                    {"Services main"}
                                  </h3>
                                }
                              />
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column__zdv9D
                              )}
                            >
                              <ServicesWhite
                                className={classNames(
                                  "__wab_instance",
                                  sty.servicesWhite___029Kx
                                )}
                                slot={
                                  <h3
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h3,
                                      projectcss.__wab_text,
                                      sty.h3__rfI68
                                    )}
                                  >
                                    {"Services main"}
                                  </h3>
                                }
                              />
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column__a35Hj
                              )}
                            >
                              <ServicesWhite
                                className={classNames(
                                  "__wab_instance",
                                  sty.servicesWhite__ri81S
                                )}
                                slot={
                                  <h3
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h3,
                                      projectcss.__wab_text,
                                      sty.h3__wpk42
                                    )}
                                  >
                                    {"Services main"}
                                  </h3>
                                }
                              />
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>
                    </p.Stack>
                  </p.Stack>
                ) : null}
              </div>
            </div>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </p.Stack>
      </div>
    </React.Fragment>
  )
}

const PlasmicDescendants = {
  root: ["root", "header", "pageBanerSection", "h1", "img", "text", "footer"],
  header: ["header"],
  pageBanerSection: ["pageBanerSection", "h1"],
  h1: ["h1"],
  img: ["img"],
  text: ["text"],
  footer: ["footer"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicServices__ArgProps,
      internalVariantPropNames: PlasmicServices__VariantProps,
    })

    return PlasmicServices__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicServices"
  } else {
    func.displayName = `PlasmicServices.${nodeName}`
  }
  return func
}

export const PlasmicServices = Object.assign(
  // Top-level PlasmicServices renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    pageBanerSection: makeNodeComponent("pageBanerSection"),
    h1: makeNodeComponent("h1"),
    img: makeNodeComponent("img"),
    text: makeNodeComponent("text"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicServices
    internalVariantProps: PlasmicServices__VariantProps,
    internalArgProps: PlasmicServices__ArgProps,
  }
)

export default PlasmicServices
/* prettier-ignore-end */
