// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sSe8AoDiAW5DkmycE76RKb
// Component: 6BXtrSevg1h6js
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import * as ph from "@plasmicapp/host"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"
import Header from "../../Header" // plasmic-import: rlLZVswJyeOUp/component
import ServicesWhite from "../../ServicesWhite" // plasmic-import: q3dvYXhBAjM3ih/component
import Footer from "../../Footer" // plasmic-import: aKMJC5Su_PgNb/component
import { useScreenVariants as useScreenVariantsxe8Uhzv7PeLJgW } from "./PlasmicGlobalVariant__Screen" // plasmic-import: XE8Uhzv7PeLJgW/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css"
import * as projectcss from "./plasmic_rva_new.module.css" // plasmic-import: sSe8AoDiAW5DkmycE76RKb/projectcss
import * as sty from "./PlasmicWhatWeDo.module.css" // plasmic-import: 6BXtrSevg1h6js/css
import leaves7194981JpgJtx9MHb from "./images/leaves7194981Jpg.jpeg" // plasmic-import: _JTX-9mHb/picture
import goldSilverChessChessBoardGameBusinessMetaphorLeadershipConceptjpgEqdqyQex5 from "./images/goldSilverChessChessBoardGameBusinessMetaphorLeadershipConceptjpg.jpeg" // plasmic-import: eqdqyQEX5/picture
import businessConceptSideViewWomanBuildingUpTowerFromWoodenBlocksjpgCHmOb6Ior from "./images/businessConceptSideViewWomanBuildingUpTowerFromWoodenBlocksjpg.jpeg" // plasmic-import: CHmOB6IOR/picture
import a2BHighpngZZbVfuKq from "./images/a2BHighpng.png" // plasmic-import: z_zbVfuKQ/picture
import technologyG800018Ba31920JpgKQi3MisXo from "./images/technologyG800018Ba31920Jpg.jpeg" // plasmic-import: kQI3misXO/picture
import riskpng2N9FlmMI from "./images/riskpng.png" // plasmic-import: 2n9FlmM-i/picture

export const PlasmicWhatWeDo__VariantProps = new Array()

export const PlasmicWhatWeDo__ArgProps = new Array()

function PlasmicWhatWeDo__RenderFunc(props) {
  const { variants, overrides, forNode } = props
  const $ctx = ph.useDataEnv?.() || {}
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args])
  const $props = args
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsxe8Uhzv7PeLJgW(),
  })

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"pageBanerSection"}
            data-plasmic-override={overrides.pageBanerSection}
            className={classNames(projectcss.all, sty.pageBanerSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__sfrl6)}>
              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                {"wHAT WE DO"}
              </h1>
            </div>
          </div>

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__rnTT)}>
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__w7RnU)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__iy5Ev)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column___2Kegg)}
                    >
                      <ServicesWhite
                        className={classNames(
                          "__wab_instance",
                          sty.servicesWhite__rGd6D
                        )}
                        slot={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__cyl0M
                            )}
                          >
                            {"New business and product launch"}
                          </h3>
                        }
                        slot2={
                          "Our deep end to end lending experience, coupled with a very pragmatic approach, makes us an ideal partner to drive the launch of new products and businesses"
                        }
                      />
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__ikN4H)}
                    >
                      <ServicesWhite
                        className={classNames(
                          "__wab_instance",
                          sty.servicesWhite__wUvVs
                        )}
                        slot={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__wfNFz
                            )}
                          >
                            {"Strategy review"}
                          </h3>
                        }
                        slot2={
                          "We have assisted a number of listed companies in crafting their new strategy and revamping their strategy during phases of market transformation."
                        }
                      />
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__w8Q2L)}
                    >
                      <ServicesWhite
                        className={classNames(
                          "__wab_instance",
                          sty.servicesWhite__fu9Jr
                        )}
                        slot={
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__i5VKw
                            )}
                          >
                            {"Transform, restructure, manage change"}
                          </h3>
                        }
                        slot2={
                          "We lead transformational programs aimed at reducing the cost base, reorganising teams and align team accountability to profit levers"
                        }
                      />
                    </div>
                  </p.Stack>
                </p.Stack>
              ) : null}

              <div className={classNames(projectcss.all, sty.freeBox__dtBcc)}>
                <div className={classNames(projectcss.all, sty.columns__vS5UA)}>
                  <div
                    className={classNames(projectcss.all, sty.column__krE2S)}
                  >
                    <ServicesWhite
                      className={classNames(
                        "__wab_instance",
                        sty.servicesWhite__sqJ9Y
                      )}
                      slot={
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__uxdSa
                          )}
                        >
                          {"Streamline and digitise"}
                        </h3>
                      }
                      slot2={
                        "We lead streamlining of processes and use new lean technology to automate and digitise operations and user experience"
                      }
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__oOo3J)}
                  >
                    <ServicesWhite
                      className={classNames(
                        "__wab_instance",
                        sty.servicesWhite__fW0So
                      )}
                      slot={
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__qSq2W
                          )}
                        >
                          {"Analytics for business decisions"}
                        </h3>
                      }
                      slot2={
                        "We inform pivotal business decisions extracting insights from the available data utilising advanced analytical techniques"
                      }
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__lhW3O)}
                  >
                    <ServicesWhite
                      className={classNames(
                        "__wab_instance",
                        sty.servicesWhite__ibope
                      )}
                      slot={
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__oqXzi
                          )}
                        >
                          {"Risk management"}
                        </h3>
                      }
                      slot2={
                        "We have significant senior line management experience in Financial and Non-Financial Risk Management within Banking and Lending"
                      }
                    />
                  </div>
                </div>
              </div>
            </div>
          </section>

          <div className={classNames(projectcss.all, sty.freeBox__eNde6)}>
            <div className={classNames(projectcss.all, sty.columns__dRmx4)}>
              <div className={classNames(projectcss.all, sty.column__sJ3A2)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__i2Uo7)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: leaves7194981JpgJtx9MHb,
                    fullWidth: 6240,
                    fullHeight: 4160,
                    aspectRatio: undefined,
                  }}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__cjldu)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__n6Ata
                  )}
                >
                  {
                    "New business and product launch\n\nWe have led or assisted the development & launch of several new businesses and products, often in record time & exceeding targets, while building sustainable internal capabilities\n\nCredit card business\n\nNon-prime lending business\n\nAuto lending product\n\nFully digital business lending product\n\nBuy Now Pay Later"
                  }
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__zwJ7H)}>
              <div className={classNames(projectcss.all, sty.columns__eG0Ny)}>
                <div className={classNames(projectcss.all, sty.column__ux8N)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wXml8
                    )}
                  >
                    {
                      "Strategy review\n\nWe have assisted a number of listed companies in crafting their new strategy and revamping their strategy during phases of market transformation.\n\nNeo-bank\n\nDomestic payment provider\n\nAuto lender\n\nLending mortgage insurer\n\n"
                    }
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.column__vgfmR)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__jUm6J)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: goldSilverChessChessBoardGameBusinessMetaphorLeadershipConceptjpgEqdqyQex5,
                      fullWidth: 5977,
                      fullHeight: 3977,
                      aspectRatio: undefined,
                    }}
                  />
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__wcXJo)}>
              <div className={classNames(projectcss.all, sty.columns__zszXa)}>
                <div className={classNames(projectcss.all, sty.column__p5LgJ)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__fWqVd)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: businessConceptSideViewWomanBuildingUpTowerFromWoodenBlocksjpgCHmOb6Ior,
                      fullWidth: 6121,
                      fullHeight: 4344,
                      aspectRatio: undefined,
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column___5USCj)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fIgaI
                    )}
                  >
                    {
                      "Transform, restructure, manage change\n\nRestructured retail banking division to increase efficiency\n\nImplemented new organisation design following merger of a payment player\n\nRevamped group Program Management Office structure, processes and governance for wealth and banking player\n\n\n"
                    }
                  </div>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__iixB)}>
              <div className={classNames(projectcss.all, sty.columns__rv24H)}>
                <div className={classNames(projectcss.all, sty.column__wwgYs)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gwYqq
                    )}
                  >
                    {
                      "Streamline and digitise\n\nWe leverage API and automation to simplify and streamline processes delivering a better customer experience and drastically reducing cost base and turnaround time:\n\nStreamlined account opening and management process following multiple acquisitions for a financial services provider\n\nRestructured credit decision process for business lending division of a major bank reducing rework by more than 80% and decreasing average turnaround time significantly\n\nImplemented automated underwriting for lenders mortgage insurance product\n\nFully digitised account opening and credit decision for a business lender, including automating the ingestion of accounting packages data\n"
                    }
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.column___4A5B)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__js3I3)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: a2BHighpngZZbVfuKq,
                      fullWidth: 1661,
                      fullHeight: 1115,
                      aspectRatio: undefined,
                    }}
                  />
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__ayY4)}>
              <div className={classNames(projectcss.all, sty.columns__w790Z)}>
                <div className={classNames(projectcss.all, sty.column__d1Ypk)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__qNsPh)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: technologyG800018Ba31920JpgKQi3MisXo,
                      fullWidth: 1920,
                      fullHeight: 961,
                      aspectRatio: undefined,
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__cGaWs)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ra8B
                    )}
                  >
                    {
                      "Analytics for busienss decisions\n\nWe enable our clients to achieve their data science & automation aspirations while addressing resourcing, data and knowledge gaps\n\nWe have assisted clients from the initial identification of the essential data, creating data lakes, analytical and predictive models and user-friendly reporting tools\n\nWe have deployed advanced analytical models, including marketing response, new and existing customer underwriting, collections and capital models\n\nWe have implemented multiple monitoring and reporting tools to enable executive decisions based on facts and focused on the key business variables\n\nWe have installed robotic and offshoring capabilities to scale up in the short time efficient analytical capabilities"
                    }
                  </div>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__wr9Nm)}>
              <div className={classNames(projectcss.all, sty.columns__qeAsh)}>
                <div className={classNames(projectcss.all, sty.column__dlxwQ)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__g9XcA
                    )}
                  >
                    {
                      "Risk management\n'\n'We have extensive line management experience in Financial and Non-Financial Risk Management within Banking and Lending\n\nWe have formulated credit policies for new products, or refinement of existing policies due to regulatory, product or market changes\n\nFor automated retail products, we have built operational risk controls into workflows and systems\n\nSet up and optimised risk and governance frameworks, including staffing structures\n\n"
                    }
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.column__aqKu6)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__ckkll)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: riskpng2N9FlmMI,
                      fullWidth: 1280,
                      fullHeight: 720,
                      aspectRatio: undefined,
                    }}
                  />
                </div>
              </div>
            </div>
          </div>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </p.Stack>
      </div>
    </React.Fragment>
  )
}

const PlasmicDescendants = {
  root: ["root", "header", "pageBanerSection", "h1", "section", "footer"],
  header: ["header"],
  pageBanerSection: ["pageBanerSection", "h1"],
  h1: ["h1"],
  section: ["section"],
  footer: ["footer"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicWhatWeDo__ArgProps,
          internalVariantPropNames: PlasmicWhatWeDo__VariantProps,
        }),

      [props, nodeName]
    )

    return PlasmicWhatWeDo__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicWhatWeDo"
  } else {
    func.displayName = `PlasmicWhatWeDo.${nodeName}`
  }
  return func
}

export const PlasmicWhatWeDo = Object.assign(
  // Top-level PlasmicWhatWeDo renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    pageBanerSection: makeNodeComponent("pageBanerSection"),
    h1: makeNodeComponent("h1"),
    section: makeNodeComponent("section"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicWhatWeDo
    internalVariantProps: PlasmicWhatWeDo__VariantProps,
    internalArgProps: PlasmicWhatWeDo__ArgProps,
  }
)

export default PlasmicWhatWeDo
/* prettier-ignore-end */
