// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sSe8AoDiAW5DkmycE76RKb
// Component: w9bR5wayqCyrZI
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import * as ph from "@plasmicapp/host"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"
import Header from "../../Header" // plasmic-import: rlLZVswJyeOUp/component
import Button from "../../Button" // plasmic-import: AI4dzLfJKZOBy/component
import Footer from "../../Footer" // plasmic-import: aKMJC5Su_PgNb/component
import { useScreenVariants as useScreenVariantsxe8Uhzv7PeLJgW } from "./PlasmicGlobalVariant__Screen" // plasmic-import: XE8Uhzv7PeLJgW/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css"
import * as projectcss from "./plasmic_rva_new.module.css" // plasmic-import: sSe8AoDiAW5DkmycE76RKb/projectcss
import * as sty from "./PlasmicContactUs.module.css" // plasmic-import: w9bR5wayqCyrZI/css
import LoactionVectorsvgIcon from "./icons/PlasmicIcon__LoactionVectorsvg" // plasmic-import: sZZ-kNTMVh1HTC/icon
import PhoneVectorsvgIcon from "./icons/PlasmicIcon__PhoneVectorsvg" // plasmic-import: DMyOYcOD0Mx0oQ/icon
import EmailVectorsvgIcon from "./icons/PlasmicIcon__EmailVectorsvg" // plasmic-import: 5zniIeEO8fPah3/icon
import globeTrotter18280791920JpgEPbCfJl8PPrF46 from "./images/globeTrotter18280791920Jpg.jpeg" // plasmic-import: EPbCfJL8PPrF46/picture

export const PlasmicContactUs__VariantProps = new Array()

export const PlasmicContactUs__ArgProps = new Array()

export const defaultContactUs__Args = {}

function PlasmicContactUs__RenderFunc(props) {
  const { variants, overrides, forNode } = props
  const args = Object.assign({}, defaultContactUs__Args, props.args)
  const $props = args
  const $ctx = ph.useDataEnv?.() || {}
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsxe8Uhzv7PeLJgW(),
  })

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"pageBanerSection"}
            data-plasmic-override={overrides.pageBanerSection}
            className={classNames(projectcss.all, sty.pageBanerSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__krabV)}>
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__n9612
                )}
              >
                {"Contact Us"}
              </h1>
            </div>
          </div>

          <section className={classNames(projectcss.all, sty.section__phVw3)}>
            <div className={classNames(projectcss.all, sty.freeBox__gpDt8)}>
              <div className={classNames(projectcss.all, sty.freeBox__knyks)}>
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___8Qt3W)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.columns__fFd1G)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__r6Oqv
                        )}
                      >
                        <p.PlasmicImg
                          data-plasmic-name={"img"}
                          data-plasmic-override={overrides.img}
                          alt={""}
                          className={classNames(sty.img)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: globeTrotter18280791920JpgEPbCfJl8PPrF46,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined,
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___6SRyh
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__t9GF
                          )}
                        >
                          <h1
                            className={classNames(
                              projectcss.all,
                              projectcss.h1,
                              projectcss.__wab_text,
                              sty.h1__qlAu
                            )}
                          >
                            {"Get In touch"}
                          </h1>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__x23Ac
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam"
                            }
                          </div>

                          <p.Stack
                            as={"div"}
                            data-plasmic-name={"formContainer2"}
                            data-plasmic-override={overrides.formContainer2}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.formContainer2
                            )}
                          >
                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.columns__vAb4W
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column__eVrZh
                                )}
                              >
                                <input
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.input,
                                    sty.textInput__ij1N5
                                  )}
                                  placeholder={"First name"}
                                  size={1}
                                  type={"text"}
                                  value={""}
                                />
                              </div>

                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column__znSju
                                )}
                              >
                                <input
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.input,
                                    sty.textInput__jI94K
                                  )}
                                  placeholder={"Last name"}
                                  size={1}
                                  type={"text"}
                                  value={""}
                                />
                              </div>

                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column__xYtGw
                                )}
                              >
                                <input
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.input,
                                    sty.textInput___0Y1BV
                                  )}
                                  placeholder={"Email address"}
                                  size={1}
                                  type={"text"}
                                  value={""}
                                />
                              </div>

                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column__aNz1G
                                )}
                              >
                                <input
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.input,
                                    sty.textInput___2Aa5R
                                  )}
                                  placeholder={"Phone number"}
                                  size={1}
                                  type={"text"}
                                  value={""}
                                />
                              </div>
                            </p.Stack>

                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.columns__qo4Zy
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column__sFev
                                )}
                              >
                                <input
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.input,
                                    sty.textInput__dbtNa
                                  )}
                                  placeholder={"Company"}
                                  size={1}
                                  type={"text"}
                                  value={""}
                                />
                              </div>

                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column__rqiQ2
                                )}
                              >
                                <textarea
                                  data-plasmic-name={"textarea"}
                                  data-plasmic-override={overrides.textarea}
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.textarea,
                                    sty.textarea
                                  )}
                                  placeholder={"Message"}
                                  value={""}
                                />

                                <Button
                                  data-plasmic-name={"button"}
                                  data-plasmic-override={overrides.button}
                                  className={classNames(
                                    "__wab_instance",
                                    sty.button
                                  )}
                                  color={"blackCoffee"}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__mU8Qv
                                    )}
                                  >
                                    {"Send Message"}
                                  </div>
                                </Button>
                              </div>
                            </p.Stack>
                          </p.Stack>
                        </p.Stack>
                      </div>
                    </p.Stack>
                  </p.Stack>
                ) : null}
              </div>
            </div>
          </section>

          <section className={classNames(projectcss.all, sty.section__uqbfR)}>
            <div className={classNames(projectcss.all, sty.freeBox__pbYFy)}>
              <div className={classNames(projectcss.all, sty.freeBox__i9Bun)}>
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__miLeU)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.columns__kjgoZ)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__kXeAp
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___9Af3Y
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__fwYxE
                            )}
                          >
                            <LoactionVectorsvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__uur7K
                              )}
                              role={"img"}
                            />
                          </div>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___3QHJe
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__nIBwh
                              )}
                            >
                              {"Address"}
                            </h3>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__zqbf
                              )}
                            >
                              {"121 state lorem state"}
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(projectcss.all, sty.column__tS8T)}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__trmYm
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__tiIH
                            )}
                          >
                            <PhoneVectorsvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__hWH6
                              )}
                              role={"img"}
                            />
                          </div>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__qdlf5
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__oQxC
                              )}
                            >
                              {"Phone"}
                            </h3>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__asnBn
                              )}
                            >
                              {"888888885588"}
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__t7Ckw
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__aH57S
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__yIr
                            )}
                          >
                            <EmailVectorsvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__i503F
                              )}
                              role={"img"}
                            />
                          </div>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__pQ9Dh
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3___5Er0
                              )}
                            >
                              {"Email"}
                            </h3>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__jnb16
                              )}
                            >
                              {"Info@gmail.com"}
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>
                    </p.Stack>
                  </p.Stack>
                ) : null}
              </div>
            </div>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </p.Stack>
      </div>
    </React.Fragment>
  )
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "pageBanerSection",
    "img",
    "formContainer2",
    "textarea",
    "button",
    "footer",
  ],

  header: ["header"],
  pageBanerSection: ["pageBanerSection"],
  img: ["img"],
  formContainer2: ["formContainer2", "textarea", "button"],
  textarea: ["textarea"],
  button: ["button"],
  footer: ["footer"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicContactUs__ArgProps,
      internalVariantPropNames: PlasmicContactUs__VariantProps,
    })

    return PlasmicContactUs__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicContactUs"
  } else {
    func.displayName = `PlasmicContactUs.${nodeName}`
  }
  return func
}

export const PlasmicContactUs = Object.assign(
  // Top-level PlasmicContactUs renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    pageBanerSection: makeNodeComponent("pageBanerSection"),
    img: makeNodeComponent("img"),
    formContainer2: makeNodeComponent("formContainer2"),
    textarea: makeNodeComponent("textarea"),
    button: makeNodeComponent("button"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicContactUs
    internalVariantProps: PlasmicContactUs__VariantProps,
    internalArgProps: PlasmicContactUs__ArgProps,
  }
)

export default PlasmicContactUs
/* prettier-ignore-end */
