// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sSe8AoDiAW5DkmycE76RKb
// Component: HkG6nEWkUxGK_
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import * as ph from "@plasmicapp/host"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
} from "@plasmicapp/react-web"
import Header from "../../Header" // plasmic-import: rlLZVswJyeOUp/component
import Fig from "../../Fig" // plasmic-import: _DbnGlNkMg/component
import CtaBottom from "../../CtaBottom" // plasmic-import: aZrFk0trqYG6jU/component
import Footer from "../../Footer" // plasmic-import: aKMJC5Su_PgNb/component
import "@plasmicapp/react-web/lib/plasmic.css"
import * as projectcss from "./plasmic_rva_new.module.css" // plasmic-import: sSe8AoDiAW5DkmycE76RKb/projectcss
import * as sty from "./PlasmicHome.module.css" // plasmic-import: HkG6nEWkUxGK_/css
import rvaTriangle2PngZCIWyJrt from "./images/rvaTriangle2Png.png" // plasmic-import: zC_IWyJRT/picture

export const PlasmicHome__VariantProps = new Array()

export const PlasmicHome__ArgProps = new Array()

function PlasmicHome__RenderFunc(props) {
  const { variants, overrides, forNode } = props
  const $ctx = ph.useDataEnv?.() || {}
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args])
  const $props = args
  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          {true ? (
            <div
              data-plasmic-name={"hero"}
              data-plasmic-override={overrides.hero}
              className={classNames(projectcss.all, sty.hero)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__ab4Ic)}
                displayHeight={"665px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: rvaTriangle2PngZCIWyJrt,
                  fullWidth: 958,
                  fullHeight: 677,
                  aspectRatio: undefined,
                }}
              />

              <Fig
                data-plasmic-name={"triangle"}
                data-plasmic-override={overrides.triangle}
                className={classNames("__wab_instance", sty.triangle)}
              />
            </div>
          ) : null}
          {true ? (
            <div
              data-plasmic-name={"companiesSection"}
              data-plasmic-override={overrides.companiesSection}
              className={classNames(projectcss.all, sty.companiesSection)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"container2"}
                data-plasmic-override={overrides.container2}
                hasGap={true}
                className={classNames(projectcss.all, sty.container2)}
              >
                <h2
                  data-plasmic-name={"h2"}
                  data-plasmic-override={overrides.h2}
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2
                  )}
                >
                  {"We work with local businesses"}
                </h2>

                <div
                  className={classNames(projectcss.all, sty.freeBox___4Hayf)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__ycGip)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__faU7H)}
                      displayHeight={"48px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      src={
                        "https://plasmic-ray.s3.us-west-2.amazonaws.com/logo-strapi.svg"
                      }
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__fjh8N)}
                      displayHeight={"48px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      src={
                        "https://plasmic-ray.s3.us-west-2.amazonaws.com/logo-segment.svg"
                      }
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__nGvoU)}
                      displayHeight={"48px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      src={
                        "https://plasmic-ray.s3.us-west-2.amazonaws.com/logo-xstate.svg"
                      }
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___0DcrR)}
                      displayHeight={"48px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      src={
                        "https://plasmic-ray.s3.us-west-2.amazonaws.com/logo-mapbox.svg"
                      }
                    />
                  </p.Stack>
                </div>
              </p.Stack>
            </div>
          ) : null}
          {true ? (
            <CtaBottom
              data-plasmic-name={"ctaBottom"}
              data-plasmic-override={overrides.ctaBottom}
              className={classNames("__wab_instance", sty.ctaBottom)}
            />
          ) : null}
          {true ? (
            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          ) : null}
        </p.Stack>
      </div>
    </React.Fragment>
  )
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "hero",
    "triangle",
    "companiesSection",
    "container2",
    "h2",
    "ctaBottom",
    "footer",
  ],

  header: ["header"],
  hero: ["hero", "triangle"],
  triangle: ["triangle"],
  companiesSection: ["companiesSection", "container2", "h2"],
  container2: ["container2", "h2"],
  h2: ["h2"],
  ctaBottom: ["ctaBottom"],
  footer: ["footer"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHome__ArgProps,
          internalVariantPropNames: PlasmicHome__VariantProps,
        }),

      [props, nodeName]
    )

    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicHome"
  } else {
    func.displayName = `PlasmicHome.${nodeName}`
  }
  return func
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    hero: makeNodeComponent("hero"),
    triangle: makeNodeComponent("triangle"),
    companiesSection: makeNodeComponent("companiesSection"),
    container2: makeNodeComponent("container2"),
    h2: makeNodeComponent("h2"),
    ctaBottom: makeNodeComponent("ctaBottom"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps,
  }
)

export default PlasmicHome
/* prettier-ignore-end */
