// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sSe8AoDiAW5DkmycE76RKb
// Component: gwfbOx-ppiR7yy
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import * as ph from "@plasmicapp/host"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"
import Header from "../../Header" // plasmic-import: rlLZVswJyeOUp/component
import CaseStudiesWraper from "../../CaseStudiesWraper" // plasmic-import: 8-mbWFXVtuiyeU/component
import CtaBottom from "../../CtaBottom" // plasmic-import: aZrFk0trqYG6jU/component
import Footer from "../../Footer" // plasmic-import: aKMJC5Su_PgNb/component
import { useScreenVariants as useScreenVariantsxe8Uhzv7PeLJgW } from "./PlasmicGlobalVariant__Screen" // plasmic-import: XE8Uhzv7PeLJgW/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css"
import * as projectcss from "./plasmic_rva_new.module.css" // plasmic-import: sSe8AoDiAW5DkmycE76RKb/projectcss
import * as sty from "./PlasmicStories.module.css" // plasmic-import: gwfbOx-ppiR7yy/css
import girls18285391920JpgZd237MRhxc0C7B from "./images/girls18285391920Jpg.jpeg" // plasmic-import: zd237mRhxc0c7B/picture
import woman32879561920JpgE5H1EGp7Yidpwp from "./images/woman32879561920Jpg.jpeg" // plasmic-import: E5H1eGp7yidpwp/picture
import girl18484541920JpgOFyq9IWGp5UgNb from "./images/girl18484541920Jpg.jpeg" // plasmic-import: oFYQ9iWGp5UgNb/picture
import girl23664381920JpgRfrxgNvc3QWdYi from "./images/girl23664381920Jpg.jpeg" // plasmic-import: rfrxgNvc3QWdYI/picture
import woman31165871920JpgBUzljUSlpw6BAm from "./images/woman31165871920Jpg.jpeg" // plasmic-import: bUzljUSlpw6bAm/picture
import girl17750351920Jpg97K8Wi06ZSp4Se from "./images/girl17750351920Jpg.jpeg" // plasmic-import: 97K8wi06zSp4Se/picture

export const PlasmicStories__VariantProps = new Array()

export const PlasmicStories__ArgProps = new Array()

export const defaultStories__Args = {}

function PlasmicStories__RenderFunc(props) {
  const { variants, overrides, forNode } = props
  const args = Object.assign({}, defaultStories__Args, props.args)
  const $props = args
  const $ctx = ph.useDataEnv?.() || {}
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsxe8Uhzv7PeLJgW(),
  })

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"pageBanerSection"}
            data-plasmic-override={overrides.pageBanerSection}
            className={classNames(projectcss.all, sty.pageBanerSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__bV9Gt)}>
              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                {"Stories"}
              </h1>
            </div>
          </div>

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <div className={classNames(projectcss.all, sty.freeBox___0Sfqp)}>
              <div className={classNames(projectcss.all, sty.freeBox__bO2In)}>
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__ydasX)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"columns"}
                      data-plasmic-override={overrides.columns}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.columns)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__dtBhw
                        )}
                      >
                        <CaseStudiesWraper
                          className={classNames(
                            "__wab_instance",
                            sty.caseStudiesWraper___5UBwq
                          )}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__tW6S3
                        )}
                      >
                        <CaseStudiesWraper
                          className={classNames(
                            "__wab_instance",
                            sty.caseStudiesWraper__eVul
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__uu5Jg)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"auto"}
                            loading={"lazy"}
                            src={{
                              src: girls18285391920JpgZd237MRhxc0C7B,
                              fullWidth: 1920,
                              fullHeight: 1280,
                              aspectRatio: undefined,
                            }}
                          />
                        </CaseStudiesWraper>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___1TZm
                        )}
                      >
                        <CaseStudiesWraper
                          className={classNames(
                            "__wab_instance",
                            sty.caseStudiesWraper__qrXev
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__ipNWq)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"auto"}
                            loading={"lazy"}
                            src={{
                              src: woman32879561920JpgE5H1EGp7Yidpwp,
                              fullWidth: 1920,
                              fullHeight: 1280,
                              aspectRatio: undefined,
                            }}
                          />
                        </CaseStudiesWraper>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__sw69N
                        )}
                      >
                        <CaseStudiesWraper
                          className={classNames(
                            "__wab_instance",
                            sty.caseStudiesWraper__frHQv
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img___2Nms)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"auto"}
                            loading={"lazy"}
                            src={{
                              src: girl18484541920JpgOFyq9IWGp5UgNb,
                              fullWidth: 1920,
                              fullHeight: 1279,
                              aspectRatio: undefined,
                            }}
                          />
                        </CaseStudiesWraper>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___2NueV
                        )}
                      >
                        <CaseStudiesWraper
                          className={classNames(
                            "__wab_instance",
                            sty.caseStudiesWraper__nGaO
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__gdESh)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"auto"}
                            loading={"lazy"}
                            src={{
                              src: girl23664381920JpgRfrxgNvc3QWdYi,
                              fullWidth: 1920,
                              fullHeight: 1280,
                              aspectRatio: undefined,
                            }}
                          />
                        </CaseStudiesWraper>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__gsPwb
                        )}
                      >
                        <CaseStudiesWraper
                          className={classNames(
                            "__wab_instance",
                            sty.caseStudiesWraper___0RAoK
                          )}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__l3Sb2
                        )}
                      >
                        <CaseStudiesWraper
                          className={classNames(
                            "__wab_instance",
                            sty.caseStudiesWraper___6TSlB
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__v8Gl)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"auto"}
                            loading={"lazy"}
                            src={{
                              src: woman31165871920JpgBUzljUSlpw6BAm,
                              fullWidth: 1920,
                              fullHeight: 1279,
                              aspectRatio: undefined,
                            }}
                          />
                        </CaseStudiesWraper>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__aGy6X
                        )}
                      >
                        <CaseStudiesWraper
                          className={classNames(
                            "__wab_instance",
                            sty.caseStudiesWraper___83Kly
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__zBbrh)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"auto"}
                            loading={"lazy"}
                            src={{
                              src: girl17750351920Jpg97K8Wi06ZSp4Se,
                              fullWidth: 1920,
                              fullHeight: 1191,
                              aspectRatio: undefined,
                            }}
                          />
                        </CaseStudiesWraper>
                      </div>
                    </p.Stack>
                  </p.Stack>
                ) : null}
              </div>
            </div>
          </section>

          <CtaBottom
            data-plasmic-name={"ctaBottom"}
            data-plasmic-override={overrides.ctaBottom}
            className={classNames("__wab_instance", sty.ctaBottom)}
          />

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </p.Stack>
      </div>
    </React.Fragment>
  )
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "pageBanerSection",
    "h1",
    "section",
    "columns",
    "ctaBottom",
    "footer",
  ],

  header: ["header"],
  pageBanerSection: ["pageBanerSection", "h1"],
  h1: ["h1"],
  section: ["section", "columns"],
  columns: ["columns"],
  ctaBottom: ["ctaBottom"],
  footer: ["footer"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicStories__ArgProps,
      internalVariantPropNames: PlasmicStories__VariantProps,
    })

    return PlasmicStories__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicStories"
  } else {
    func.displayName = `PlasmicStories.${nodeName}`
  }
  return func
}

export const PlasmicStories = Object.assign(
  // Top-level PlasmicStories renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    pageBanerSection: makeNodeComponent("pageBanerSection"),
    h1: makeNodeComponent("h1"),
    section: makeNodeComponent("section"),
    columns: makeNodeComponent("columns"),
    ctaBottom: makeNodeComponent("ctaBottom"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicStories
    internalVariantProps: PlasmicStories__VariantProps,
    internalArgProps: PlasmicStories__ArgProps,
  }
)

export default PlasmicStories
/* prettier-ignore-end */
